Codecleaning (Closes #49)
CoraLibre/CoraLibre-android-sdk pull request #50
Opened 2020-09-04 13:20 UTC by haitrec

I removed many files that we probably don't need anymore, and removed some methods and fields from the remaining code (in particular in AppConfigManager). I moved some of the remaining files into subpackages of _sdk.internal_ where I think they fit best.
I also moved some of the classfiles that are currently not in use, but might be useful in the future, into _internal.error.old_ and _internal.bluetooth.old_. In the future we can move them into the respective packages (_internal.error_, _internal.bluetooth_) if they are still required, or delete them, if we do not need them for CoraLibre. For the bluetooth classes I would be glad if @theScrabi could check, if these should be deleted as well.

Before merging this PR I'd recommend to merge all ongoing work into master. Otherwise the many deletions and file movements in this PR might result in difficult/annoying rebasing.

2020-09-06 12:33 UTC, Stypox requested changes
The things you removed look reasonable, so I think this is good.

2020-09-06 12:33 UTC, Stypox commented on CHANGELOG.md
> -- Rename to CoraLibre-android-sdk
These three lines are relevant to coralibre: is it ok to remove them? I mean, changelog files are mostly useless if we will be using GitHub's releases, but anyway I am not completely sure if this should be removed

2020-09-08 19:25 UTC, theScrabi approved these changes
LFTM :)

2020-09-10 13:48 UTC, Stypox approved these changes

2020-09-10 14:00 UTC, Stypox commented
Ready for merge

2020-09-10 14:46 UTC, merged